---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-files
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      app: wordpress
      component: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
    component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      component: web
  template:
    metadata:
      labels:
        app: wordpress
        component: web
    spec:
      volumes:
        - name: wordpress-files
          persistentVolumeClaim:
            claimName: wordpress-files
      containers:
        - name: wordpress
          image: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: db
            - name: WORDPRESS_DB_USER
              value: exampleuser
            - name: WORDPRESS_DB_PASSWORD
              value: examplepass
            - name: WORDPRESS_DB_NAME
              value: exampledb
          volumeMounts:
            - name: wordpress-files
              mountPath: /var/www/html
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
    component: web
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: wordpress
    component: web
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-files
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      app: wordpress
      component: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: wordpress
    component: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      component: db
  template:
    metadata:
      labels:
        app: wordpress
        component: db
    spec:
      volumes:
        - name: mysql-files
          persistentVolumeClaim:
            claimName: mysql-files
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_DATABASE
              value: exampledb
            - name: MYSQL_USER
              value: exampleuser
            - name: MYSQL_PASSWORD
              value: examplepass
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: '1'
          volumeMounts:
            - name: mysql-files
              mountPath: /var/www/html
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: wordpress
    component: db
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    component: db
